version: '3.1'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      -  8443:80

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redacted
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
